# -*- coding: utf-8 -*-
"""LLN-hat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzEF5p-KvXMwgIJ9CkXlydTCKz9UvTF7
"""

import matplotlib.pyplot as plt
import numpy as np

# 1. Set seed for reproducibility
np.random.seed(42)

# 2. Define parameters for the continuous Hat Function (Triangular) PDF
# A symmetric hat function from a=0 to b=10 peaks exactly at c=5 (the mode).
# For a symmetric triangular distribution, the expected value (mu) is exactly 5.0.
a = 0.0
b = 10.0
c = 5.0
mu = 5.0  # True theoretical mean
num_samples = 10000  # Total number of samples (n)

# 3. Generate 10,000 independent samples from the Hat/Triangular distribution
samples = np.random.triangular(left=a, mode=c, right=b, size=num_samples)

# 4. Compute the cumulative (running) sample mean
sample_sizes = np.arange(1, num_samples + 1)
running_mean = np.cumsum(samples) / sample_sizes

# 5. Print snapshot results to check convergence
print(f"Sample mean at n=10:     {running_mean[9]:.3f}")
print(f"Sample mean at n=100:    {running_mean[99]:.3f}")
print(f"Sample mean at n=1000:   {running_mean[999]:.3f}")
print(f"Sample mean at n=10000:  {running_mean[9999]:.3f}")

# 6. Plot the results
plt.figure(figsize=(10, 6))
plt.plot(
    sample_sizes,
    running_mean,
    label="Sample Mean (bar(x) n)",
    color="darkorange",
    alpha=0.8,
)
plt.axhline(
    y=mu,
    color="red",
    linestyle="--",
    linewidth=2,
    # label=f"True Expected Value ($\mu$ = {mu})",
)

# Customize the plot
plt.title(
    "Law of Large Numbers Convergence (Hat Function / Triangular PDF)", fontsize=14
)
plt.xlabel("Sample Size ($n$)", fontsize=12)
plt.ylabel("Value", fontsize=12)
plt.xscale("log")  # Using a log scale makes early fluctuations easier to see
plt.grid(True, which="both", linestyle=":", alpha=0.5)
plt.legend(fontsize=11)

# Show the plot
plt.show()