# -*- coding: utf-8 -*-
"""LLN-Gaussian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAKUgF7O4jNoWB2RFrR14Q1lntGcVvSL
"""

import numpy as np
import matplotlib.pyplot as plt
# 1. Set seed for reproducibility
np.random.seed(42)
# 2. Define parameters for the continuous Gaussian PDF
mu = 5.0 ;  sigma = 2.0
num_samples = 10000 #Total number of samples, n
# 3. Generate 10,000 independent samples from N(mu, sigma^2)
samples = np.random.normal(loc=mu, scale=sigma, size=num_samples)
# 4. Compute the cumulative (running) sample mean
sample_sizes = np.arange(1, num_samples + 1)
running_mean = np.cumsum(samples) / sample_sizes
# 5. Print snapshot results to check convergence
print(f"Sample mean at n=10:     {running_mean[9]:.3f}")
print(f"Sample mean at n=100:    {running_mean[99]:.3f}")
print(f"Sample mean at n=1000:   {running_mean[999]:.3f}")
print(f"Sample mean at n=10000:  {running_mean[9999]:.3f}")
# 6. Plot the results
plt.figure(figsize=(10, 6))
plt.plot(  sample_sizes,  running_mean,   label="Sample Mean ($\\bar{X}_n$)",  color="blue",  alpha=0.8,)
plt.axhline(    y=mu,    color="red",    linestyle="--",    linewidth=2,    label=f"True Expected Value ($\\mu$ = {mu})",)
plt.title(    "Law of Large Numbers Convergence (Gaussian Distribution)", fontsize=14)
plt.xlabel("Sample Size ($n$)", fontsize=12)
plt.ylabel("Value", fontsize=12)
plt.xscale("log")
plt.grid(True, which="both", linestyle=":", alpha=0.5)
plt.legend(fontsize=11)
plt.show()  # Show the plot